### ISSUE TITLE
xhr.js does not support shimmed HTML imports

### ISSUE THREAD

**Issue by kristfal** [driftyco/cordova-plugin-wkwebview-engine#50]
Hey,

trying to use HTML imports such as `<link rel="import" href="elements/app-elements.html">` with [webcomponents.js](https://github.com/webcomponents/webcomponentsjs) silently fails with this fork of the wkwebview engine. 

For now, the only workaround seems to be using a local webserver.

Would be really awesome if this plugin added a custom shimmed HTML import to support this upcoming standard.

**Comment by manucorporat** [comment]
@kristfal xhr.js only can intercept JS XMLHTTPRequests. 

>"silently fails"

did you debug remotely with Safari WebTools?

**Comment by kristfal** [comment]
@manucorporat Yes. Attempted both to import inline in `index.html` and use `location.reload()` to catch any errors and to import via javascript through:

```
var elements = document.createElement('link');
      elements.rel = 'import';
      elements.href = 'elements/app-elements.html';

      document.head.appendChild(elements);
```

The latter alternative inserts the import in the `head` tag, but does not actually trigger any import. Think there is any way around it, or should we just jump over to the web server option?

**Comment by manucorporat** [comment]
@kristfal not exactly, that is still using some API that is not XHR.
I meant, https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

The reason, html is not working is because it is not a supported standard by WKWebkit nor Safari:
http://caniuse.com/#feat=imports

We can't do not anything, this is an internal thing that should be implemented by the WebKit at Apple.

I suggest you to use a different approach, maybe angular2/ionic2? or doing the XHR requests manually and then inline the content inside some HTML element with the innerHTML property.
