### ISSUE TITLE
Listening for web events

### ISSUE THREAD

**Issue by olostan** [driftyco/cordova-plugin-wkwebview-engine#58]
Because "you cannot listen to web events in the same fashion as the standard InAppBrowser" there is not possible to close auth popups. See more details on
https://github.com/nraboy/ng2-cordova-oauth/issues/33

It would be nice to provide same functionality so libraries like "ng2-cordova-oath" would be able to react on web events and close popups.

**Comment by manucorporat** [comment]
What's the issue?

**Comment by olostan** [comment]
as reported by @nraboy, this plugin does not support listening to web event. The issue is about adding "web events" support to wkwebview engine if it is possible so other libraries can "listen to web events in the same fashion as the standard InAppBrowser".

**Comment by manucorporat** [comment]
well, I am not 100% sure what "web events" means, but I don't think @nraboy is right. There is nothing that stops WKWebview to receive events from InAppBrowser.

It is not working because a bug in InAppBrowser, a bug that has been fixed by us https://github.com/apache/cordova-plugin-inappbrowser/pull/187
but not merged.
