### ISSUE TITLE
Images are not visible

### ISSUE THREAD

**Issue by uaza** [driftyco/cordova-plugin-wkwebview-engine#9]
My images are not visible anymore with WKWebView. I don't have any display problems with UIWebView.

HTML: ... `<img ng-src="{{vm.imageUri}}>`...

config.xml:
...
  `<access origin="*"/`>
  `<access origin="http://*" launch-external="yes"/`>
  `<access origin="https://*" launch-external="yes"/`>
...

It have tried the following URIs (preview_1471524559000 is the image file):

* cdvfile://localhost/library-nosync/quiply/img/group/578e1c799315c40aff094fd6/preview_1471524559000

* file:///var/mobile/Containers/Data/Application/500FE332-964A-48B9-8492-F0B4056FD2B5/Library/NoCloud/quiply/img/group/578e1c799315c40aff094fd6/preview_1471524559000

* /Library/NoCloud/quiply/img/group/578e1c799315c40aff094fd6/preview_1471524559000

Did I do something wrong?

**Comment by manucorporat** [comment]
You should always use relative paths. Can you run your app in the iPhone Simulator and attach the Safari WebTools Debugger?

1. Run the app in the simulator
2. Open Safari/Develop/Simulator/index.html
3. Reload from the webtools
4. Inspect the timeline, and console.

http://adaptivejs.mobify.com/v2.0/docs/debug-on-ios-devices-and-the-ios-simulator/

**Comment by uaza** [comment]
Thank you for your quick response!

I switched to relative paths and then I think the problem was that I tried it with live reload. Without live reload I have unfortunately the next issue. The app crashes after a view seconds (see https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/11#issuecomment-240990544)

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! Since the original bug this issue was opened for has been solved i will be closing this issue for now. Thanks for using Ionic!

**Comment by elijnzaad** [comment]
I know this issue is closed, but could you please clarify this a little bit more for me?
"Also,any relative URL can not leave the www folder where ALL the html, js, images and assets of you app should be."

I have an app for inspectors of houses that downloads images and pdf's depending on which object someone is inspecting at the moment. All this stuff gets downloaded into Library/NoCloud before the inspector starts inspecting. When the inspection is done they get removed again. So these images are not bundled with the app in the www folder, but downloaded on demand.

WKWebView does load allow loading json from Library/NoCloud by using the FileReader, but it does not allow for reading images like uaza mentioned above. Does your answer imply that is is just not possible to download and use assets on demand?

**Comment by manucorporat** [comment]
@elijnzaad the truth is: WKWebView does allow to request Library/NoCloud

Any request can not leave the the app directory.
```
file:///var/mobile/Containers/Data/Application/500FE332-964A-48B9-8492-F0B4056FD2B5/
```

so a request to:
```
file:///var/mobile/Containers/Data/Application/500FE332-964A-48B9-8492-F0B4056FD2B5/Library/NoCloud
```

since it is part of the app.


NOTE, this condition is ensured by the iOS sandbox model. You can't avoid it. This prevents an app from reading another's app content.

Right now, this plugin is even more restrictive when using the XHR channel, we block requests outside the www folder (see https://github.com/driftyco/cordova-plugin-wkwebview-engine/blob/master/src/ios/CDVWKWebViewEngine.m#L402-L407)

^ We can reevaluate the security model. Feel free to open an issue explaining why XHR can be needed outside the www/ folder.
@adamdbradley @mlynch what are the security implications of allowing requests outside the www folder?

**Comment by manucorporat** [comment]
@elijnzaad since you are not probably using XHR to request the images, could you make the URLs relative?
```
../Library/NoCloud
```
Maybe you need `../` twice. 

Also, use the safari remote inspector to debug the absolute resolved URL. Check out the resources tab http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html

**Comment by phillipplum** [comment]
@manucorporat with `../` or `../../` seems not to work :/
I download images to /Library/NoCloud and want to show the images now.

**Comment by elijnzaad** [comment]
Thanks manucorporat, but the relative paths didn't work for me either. They do get translated into absolute paths, so the problem remains (I checked the inspector for the correct path). 

So far the only way I could make it work is by using the FileReader.readAsDataURL(). It is not as clean and certainly not as quick as using a URL, but it works. Thanks for your swift reply and for you work on the plugin. It is quite a lot better than the original one and I think I will be able to use it in the forthcoming release of the app.
